version: "3.0"
services:
  backend:
    build: backend
    ports:
      - 8080:8080
      - 8081:8081
    networks:
        default:
          aliases:
            - backend

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
        default:
          aliases:
            - proxy
    volumes:
      - ./proxy/public:/var/www/html:ro
    extra_hosts:
      # this will probably not work because of network sandboxing
      - "canvas:127.0.0.1"

  render:
    build: render
    ports:
      - 8000:8000
    networks:
        default:
          aliases:
            - render
